// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: visibility/v1/visibility.proto

// Package visibility provides options for specifying visibility rules for
// Protocol Buffer entities. These rules are not inherently enforced by protoc,
// but can be referenced via static analysis to ensure they are adhered to.
// protoc-gen-visibility provides a reference implementation of such a tool.

package visibility

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode controls what may depend on a particular entity.
type Mode int32

const (
	// MODE_UNSPECIFIED defaults to MODE_PUBLIC.
	Mode_MODE_UNSPECIFIED Mode = 0
	// MODE_PUBLIC is the default visibility of entities. Any other entity may
	// import and use this entity.
	Mode_MODE_PUBLIC Mode = 1
	// MODE_SUBPACKAGES limits visibility of the entity to its package and any
	// subpackages thereof. Permissions may be expanded in the Specification.
	Mode_MODE_SUBPACKAGES Mode = 2
	// MODE_PACKAGE limits direct visibility of the entity to its package,
	// exclusively. Permissions may be expanded in the Specification.
	Mode_MODE_PACKAGE Mode = 3
	// MODE_FILE mode limits direct visibility of the entity to its containing file,
	// exclusively. Permissions may be expanded in the Specification.
	Mode_MODE_FILE Mode = 4
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_PUBLIC",
		2: "MODE_SUBPACKAGES",
		3: "MODE_PACKAGE",
		4: "MODE_FILE",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_PUBLIC":      1,
		"MODE_SUBPACKAGES": 2,
		"MODE_PACKAGE":     3,
		"MODE_FILE":        4,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_visibility_v1_visibility_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_visibility_v1_visibility_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_visibility_v1_visibility_proto_rawDescGZIP(), []int{0}
}

// Specification describes the visibility rules that govern an entity.
// Specifications are inherited from parent entities unless overridden.
type Specification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mode applies the general visibility rule for this entity.
	Mode Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=visibility.v1.Mode" json:"mode,omitempty"`
	// Packages are package names that can explicitly access this entity. A
	// package name suffixed with '.*' will include that package and any
	// subpackages.
	Packages []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
}

func (x *Specification) Reset() {
	*x = Specification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visibility_v1_visibility_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specification) ProtoMessage() {}

func (x *Specification) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_v1_visibility_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specification.ProtoReflect.Descriptor instead.
func (*Specification) Descriptor() ([]byte, []int) {
	return file_visibility_v1_visibility_proto_rawDescGZIP(), []int{0}
}

func (x *Specification) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *Specification) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

var file_visibility_v1_visibility_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Specification)(nil),
		Field:         128064,
		Name:          "visibility.v1.file_rules",
		Tag:           "bytes,128064,opt,name=file_rules",
		Filename:      "visibility/v1/visibility.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Specification)(nil),
		Field:         128064,
		Name:          "visibility.v1.message_rules",
		Tag:           "bytes,128064,opt,name=message_rules",
		Filename:      "visibility/v1/visibility.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*Specification)(nil),
		Field:         128064,
		Name:          "visibility.v1.enum_rules",
		Tag:           "bytes,128064,opt,name=enum_rules",
		Filename:      "visibility/v1/visibility.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// FileRules defines the visibility Specification for the entire file. All
	// entities in the file inherit these rules unless otherwise specified.
	//
	// optional visibility.v1.Specification file_rules = 128064;
	E_FileRules = &file_visibility_v1_visibility_proto_extTypes[0] // 👀
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// MessageRules defines the visibility Specification for a message. All
	// messages or enums nested in the message inherit these rules unless
	// otherwise specified.
	//
	// optional visibility.v1.Specification message_rules = 128064;
	E_MessageRules = &file_visibility_v1_visibility_proto_extTypes[1] // 👀
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// EnumRules defines the visibility Specification for an enum.
	//
	// optional visibility.v1.Specification enum_rules = 128064;
	E_EnumRules = &file_visibility_v1_visibility_proto_extTypes[2] // 👀
)

var File_visibility_v1_visibility_proto protoreflect.FileDescriptor

var file_visibility_v1_visibility_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x2f,
	0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x54, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x64, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x53,
	0x55, 0x42, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x04, 0x3a, 0x5b, 0x0a,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc0, 0xe8, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x64, 0x0a, 0x0d, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc0, 0xe8, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x3a, 0x5b, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc0, 0xe8, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x42, 0x43, 0x5a,
	0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x64, 0x61,
	0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_visibility_v1_visibility_proto_rawDescOnce sync.Once
	file_visibility_v1_visibility_proto_rawDescData = file_visibility_v1_visibility_proto_rawDesc
)

func file_visibility_v1_visibility_proto_rawDescGZIP() []byte {
	file_visibility_v1_visibility_proto_rawDescOnce.Do(func() {
		file_visibility_v1_visibility_proto_rawDescData = protoimpl.X.CompressGZIP(file_visibility_v1_visibility_proto_rawDescData)
	})
	return file_visibility_v1_visibility_proto_rawDescData
}

var file_visibility_v1_visibility_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_visibility_v1_visibility_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_visibility_v1_visibility_proto_goTypes = []interface{}{
	(Mode)(0),                           // 0: visibility.v1.Mode
	(*Specification)(nil),               // 1: visibility.v1.Specification
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),    // 4: google.protobuf.EnumOptions
}
var file_visibility_v1_visibility_proto_depIdxs = []int32{
	0, // 0: visibility.v1.Specification.mode:type_name -> visibility.v1.Mode
	2, // 1: visibility.v1.file_rules:extendee -> google.protobuf.FileOptions
	3, // 2: visibility.v1.message_rules:extendee -> google.protobuf.MessageOptions
	4, // 3: visibility.v1.enum_rules:extendee -> google.protobuf.EnumOptions
	1, // 4: visibility.v1.file_rules:type_name -> visibility.v1.Specification
	1, // 5: visibility.v1.message_rules:type_name -> visibility.v1.Specification
	1, // 6: visibility.v1.enum_rules:type_name -> visibility.v1.Specification
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	4, // [4:7] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_visibility_v1_visibility_proto_init() }
func file_visibility_v1_visibility_proto_init() {
	if File_visibility_v1_visibility_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_visibility_v1_visibility_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_visibility_v1_visibility_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_visibility_v1_visibility_proto_goTypes,
		DependencyIndexes: file_visibility_v1_visibility_proto_depIdxs,
		EnumInfos:         file_visibility_v1_visibility_proto_enumTypes,
		MessageInfos:      file_visibility_v1_visibility_proto_msgTypes,
		ExtensionInfos:    file_visibility_v1_visibility_proto_extTypes,
	}.Build()
	File_visibility_v1_visibility_proto = out.File
	file_visibility_v1_visibility_proto_rawDesc = nil
	file_visibility_v1_visibility_proto_goTypes = nil
	file_visibility_v1_visibility_proto_depIdxs = nil
}
